version: '3.3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ecommerce-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql


networks:
  ecommerce-network:
    driver: bridge

volumes:
  mysql-data: